ALTER TYPE "VoiceStage" ADD VALUE IF NOT EXISTS 'AWAITING_NAME';
ALTER TYPE "VoiceStage" ADD VALUE IF NOT EXISTS 'AWAITING_NAME_CONFIRMATION';
ALTER TYPE "VoiceStage" ADD VALUE IF NOT EXISTS 'SAFETY_CHECK';
ALTER TYPE "VoiceStage" ADD VALUE IF NOT EXISTS 'DEVICE_CHECK';
ALTER TYPE "VoiceStage" ADD VALUE IF NOT EXISTS 'AWAITING_DOMINANT_FOOT';
ALTER TYPE "VoiceStage" ADD VALUE IF NOT EXISTS 'READY_FOR_SET_ONE';
ALTER TYPE "VoiceStage" ADD VALUE IF NOT EXISTS 'SET_ONE_IN_PROGRESS';
ALTER TYPE "VoiceStage" ADD VALUE IF NOT EXISTS 'RESTING';
ALTER TYPE "VoiceStage" ADD VALUE IF NOT EXISTS 'READY_FOR_SET_TWO';
ALTER TYPE "VoiceStage" ADD VALUE IF NOT EXISTS 'SET_TWO_IN_PROGRESS';
ALTER TYPE "VoiceStage" ADD VALUE IF NOT EXISTS 'SCORING';
ALTER TYPE "VoiceStage" ADD VALUE IF NOT EXISTS 'PAUSED';

ALTER TABLE "VoiceSession"
ADD COLUMN "userId" TEXT,
ADD COLUMN "patientName" TEXT,
ADD COLUMN "patientEmail" TEXT,
ADD COLUMN "dominantFoot" TEXT,
ADD COLUMN "deviceConnected" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "setOneSteps" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "setTwoSteps" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "lastAnnouncedStep" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "restStartedAt" TIMESTAMP(3),
ADD COLUMN "pausedStage" TEXT,
ADD COLUMN "score" DOUBLE PRECISION;

CREATE INDEX "VoiceSession_userId_updatedAt_idx"
ON "VoiceSession"("userId", "updatedAt");

ALTER TABLE "VoiceSession"
ADD CONSTRAINT "VoiceSession_userId_fkey"
FOREIGN KEY ("userId") REFERENCES "User"("id")
ON DELETE SET NULL ON UPDATE CASCADE;
